// Generated by CoffeeScript 1.6.2
(function() {
  var Colorfull, colorfull, toHex, toHsla, toRgba,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Colorfull = (function() {
    function Colorfull() {
      this.showColor = __bind(this.showColor, this);
      this.resize = __bind(this.resize, this);
      this.stop = __bind(this.stop, this);
      this.roll = __bind(this.roll, this);      this.canvas = document.getElementById('canvas');
      this.interval = 30;
      this.timer = null;
      this.color = 0;
    }

    Colorfull.prototype.init = function() {
      this.resize();
      this.ctx = this.canvas.getContext('2d');
      return this;
    };

    Colorfull.prototype.roll = function() {
      var _this = this;

      return this.timer = setInterval((function() {
        var grd;

        grd = _this.ctx.createRadialGradient(_this.canvas.width / 2, _this.canvas.height / 2, 0, _this.canvas.width / 2, _this.canvas.height / 2, (_this.canvas.width + _this.canvas.height) / 2);
        grd.addColorStop(0, "hsla(" + (_this.color % 360) + ", 100%, 50%, 1)");
        grd.addColorStop(1, "hsla(" + (_this.color % 360) + ", 20%, 50%, 1)");
        _this.ctx.fillStyle = grd;
        _this.ctx.fillRect(0, 0, _this.canvas.width, _this.canvas.height);
        return _this.color += 1;
      }), this.interval);
    };

    Colorfull.prototype.stop = function() {
      if (this.timer != null) {
        return clearInterval(this.timer);
      }
    };

    Colorfull.prototype.resize = function() {
      this.canvas.height = document.height;
      return this.canvas.width = document.width;
    };

    Colorfull.prototype.showColor = function(e) {
      var pixel;

      pixel = this.ctx.getImageData(e.clientX, e.clientY, 1, 1);
      return pixel.data;
    };

    return Colorfull;

  })();

  toRgba = function(data) {
    var a, b, g, r;

    r = data[0], g = data[1], b = data[2], a = data[3];
    return "rgba(" + r + ", " + g + ", " + b + ", " + (Number((r / 255).toFixed(2))) + ")";
  };

  toHsla = function(data) {
    var a, b, d, g, h, l, max, min, r, s, _ref;

    _ref = data.map(function(c) {
      return c / 255;
    }), r = _ref[0], g = _ref[1], b = _ref[2];
    a = data[3];
    max = Math.max(r, g, b);
    min = Math.min(r, g, b);
    l = (max + min) / 2;
    if (max === min) {
      h = s = 0;
    } else {
      d = max - min;
      s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
      switch (max) {
        case r:
          h = (g - b) / d + (g < b ? 6 : 0);
          break;
        case g:
          h = (b - r) / d + 2;
          break;
        case b:
          h = (r - g) / d + 4;
          break;
        default:
          break;
      }
      h /= 6;
    }
    return "hsla(" + (Math.round(h * 360)) + ", " + (Math.round(s * 100)) + "%, " + (Math.round(l * 100)) + "%, " + a + ")";
  };

  toHex = function(data) {
    var a, b, g, r, toFullHex;

    r = data[0], g = data[1], b = data[2], a = data[3];
    toFullHex = function(str) {
      return ('00' + str.toString(16)).substr(-2);
    };
    return "#" + (toFullHex(r)) + (toFullHex(g)) + (toFullHex(b));
  };

  colorfull = new Colorfull();

  colorfull.init().roll();

  $('#canvas').bind('mousemove', function(e) {
    var colorData, data, rgba;

    colorData = colorfull.showColor(e);
    data = [colorData[0], colorData[1], colorData[2], colorData[3]];
    if (data != null) {
      rgba = toRgba(data);
      $('#c-hex').val(toHex(data));
      $('#c-rgba').val(rgba);
      $('#c-hsla').val(toHsla(data));
      return $('.color-preview').css({
        'background': rgba
      });
    }
  });

  $('.joke').fadeOut(10000);

}).call(this);
